# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev openssl-dev libffi-dev

WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Expose port if necessary (not required for stdio)

# Default command starts the MCP server
CMD ["mcp-think-tool"]
